config/routes.rb
Portal::Application.routes.draw do
  
get "admin/index"
scope "admin" do
  resources :proyectos_users
  resources :proyectos_usuarios
  resources :integrantes
  resources :actas
  resources :foros
  resources :respuestas
  resources :comentarios
  resources :articulos
  resources :proyectos
  resources :eventos
end
  
  root :to => "home#index"
  get "home/blog"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
           can :manage, :all 
    elsif user.has_role? :miembro
            can :read, :all

            cannot :destroy, [Proyecto, User]
            cannot :create, [Proyecto, User]             
     
    end
        
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acta.rb
class Acta < ActiveRecord::Base
end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader

	belongs_to :user
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader
end

app/models/foro.rb
class Foro < ActiveRecord::Base
end

app/models/integrante.rb
class Integrante < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/proyectos_user.rb
class ProyectosUser < ActiveRecord::Base
end

app/models/respuesta.rb
class Respuesta < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


     has_many :articulos



end

app/helpers/actas_helper.rb
module ActasHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/foros_helper.rb
module ForosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/respuestas_helper.rb
module RespuestasHelper
end

app/views/admin/index.html.erb
<div class="row">
<div class="large-12 columns">
 
<!-- Navigation -->
 
<div class="row">
<div class="large-12 columns">
 

<!-- End Top Bar -->
</div>
</div>
 
<!-- End Navigation -->
 
<div class="row">
 
<!-- Side Bar -->
 
<div class="large-4 small-12 columns">
 
<%= image_tag "postit.png", :class =>"postit", :alt => "dash" %>
 

<h3>Bienvenidos</h3>
<h5 class="subheader">Estan dentro del DashBoard del portal de locxue, interactue, aporte, opine, aproveche estas herramientas.
Si tiene algun problema tecnico contactar al administrador.
</h5>

 
 
</div>
 
<!-- End Side Bar -->
 
 
<!-- Thumbnails -->
 
<div class="large-8 columns">
<div class="row">
 
<div class="large-4 small-6 columns">
<%= image_tag "itemacticulo.png", :class =>"postit", :alt => "dash" %>
 <div class="panel">
<h5><%=link_to "Articulos", articulos_path%></h5>
</div>
</div>
 
<div class="large-4 small-6 columns">
<%= image_tag "itemevento.png", :class =>"postit", :alt => "dash" %>
 <div class="panel">
<h5><%=link_to "Eventos", eventos_path%></h5>
</div>
</div>
 
<div class="large-4 small-6 columns">
<%= image_tag "itemacta.png", :class =>"postit", :alt => "dash" %>
 <div class="panel">
<h5><%=link_to "Actas", actas_path%></h5>
</div>
</div>
 
<div class="large-4 small-6 columns">
<%= image_tag "itemproyecto.png", :class =>"postit", :alt => "dash" %>
<div class="panel">
<h5><%=link_to "Proyectos", proyectos_path%></h5>
</div>
</div>
 
<div class="large-4 small-6 columns">
<%= image_tag "itemforo.png", :class =>"postit", :alt => "dash" %>
 <div class="panel">
<h5><%=link_to "Foros", foros_path%></h5>
</div>
</div>
 <div class="large-4 small-6 columns">
<%= image_tag "itemuser.png", :class =>"postit", :alt => "dash" %>
 
<div class="panel">
<h5><%=link_to "Usuarios", users_path%></h5>

</div>
</div>
</div>
 
<!-- End Thumbnails -->
 
 </div>
</div>
</div>
</div>