config/routes.rb
Portal::Application.routes.draw do
  
get "admin/index"
scope "admin" do
  resources :proyectos_users
  resources :proyectos_usuarios
  resources :integrantes
  resources :actas
  resources :foros
  resources :respuestas
  resources :comentarios
  resources :articulos
  resources :proyectos
  resources :eventos
end
  
  root :to => "home#index"
  get "home/blog"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
           can :manage, :all 
    elsif user.has_role? :miembro
            can :read, :all

            cannot :destroy, [Proyecto, User]
            cannot :create, [Proyecto, User]             
     
    end
        
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acta.rb
class Acta < ActiveRecord::Base
end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader

	belongs_to :user
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader
end

app/models/foro.rb
class Foro < ActiveRecord::Base
end

app/models/integrante.rb
class Integrante < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/proyectos_user.rb
class ProyectosUser < ActiveRecord::Base
end

app/models/respuesta.rb
class Respuesta < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


     has_many :articulos



end

app/controllers/integrantes_controller.rb
class IntegrantesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_integrante, only: [:show, :edit, :update, :destroy]

  # GET /integrantes
  # GET /integrantes.json
  def index
    @integrantes = Integrante.all
  end

  # GET /integrantes/1
  # GET /integrantes/1.json
  def show
  end

  # GET /integrantes/new
  def new
    @integrante = Integrante.new
  end

  # GET /integrantes/1/edit
  def edit
  end

  # POST /integrantes
  # POST /integrantes.json
  def create
    @integrante = Integrante.new(integrante_params)

    respond_to do |format|
      if @integrante.save
        format.html { redirect_to @integrante, notice: 'Integrante was successfully created.' }
        format.json { render action: 'show', status: :created, location: @integrante }
      else
        format.html { render action: 'new' }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /integrantes/1
  # PATCH/PUT /integrantes/1.json
  def update
    respond_to do |format|
      if @integrante.update(integrante_params)
        format.html { redirect_to @integrante, notice: 'Integrante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /integrantes/1
  # DELETE /integrantes/1.json
  def destroy
    @integrante.destroy
    respond_to do |format|
      format.html { redirect_to integrantes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_integrante
      @integrante = Integrante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def integrante_params
      params.require(:integrante).permit(:nombre, :apellido_1, :apellido_2, :perfil, :telefono, :imagen, :user_id)
    end
end

app/helpers/actas_helper.rb
module ActasHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/foros_helper.rb
module ForosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/integrantes_helper.rb
module IntegrantesHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/respuestas_helper.rb
module RespuestasHelper
end

app/views/integrantes/_form.html.erb
<%= simple_form_for(@integrante) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :apellido_1 %>
    <%= f.input :apellido_2 %>
    <%= f.input :perfil %>
    <%= f.input :telefono %>
    <%= f.input :imagen %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/integrantes/edit.html.erb
<h1>Editing integrante</h1>

<%= render 'form' %>

<%= link_to 'Show', @integrante %> |
<%= link_to 'Back', integrantes_path %>

app/views/integrantes/index.html.erb
<h1>Listing integrantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido 1</th>
      <th>Apellido 2</th>
      <th>Perfil</th>
      <th>Telefono</th>
      <th>Imagen</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @integrantes.each do |integrante| %>
      <tr>
        <td><%= integrante.nombre %></td>
        <td><%= integrante.apellido_1 %></td>
        <td><%= integrante.apellido_2 %></td>
        <td><%= integrante.perfil %></td>
        <td><%= integrante.telefono %></td>
        <td><%= integrante.imagen %></td>
        <td><%= integrante.user_id %></td>
        <td><%= link_to 'Show', integrante %></td>
        <td><%= link_to 'Edit', edit_integrante_path(integrante) %></td>
        <td><%= link_to 'Destroy', integrante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Integrante', new_integrante_path %>

app/views/integrantes/new.html.erb
<h1>New integrante</h1>

<%= render 'form' %>

<%= link_to 'Back', integrantes_path %>

app/views/integrantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @integrante.nombre %>
</p>

<p>
  <strong>Apellido 1:</strong>
  <%= @integrante.apellido_1 %>
</p>

<p>
  <strong>Apellido 2:</strong>
  <%= @integrante.apellido_2 %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @integrante.perfil %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @integrante.telefono %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @integrante.imagen %>
</p>

<p>
  <strong>User:</strong>
  <%= @integrante.user_id %>
</p>

<%= link_to 'Edit', edit_integrante_path(@integrante) %> |
<%= link_to 'Back', integrantes_path %>