config/routes.rb
Portal::Application.routes.draw do
  
get "admin/index"
scope "admin" do
  resources :proyectos_users
  resources :proyectos_usuarios
  resources :integrantes
  resources :actas
  resources :foros
  resources :respuestas
  resources :comentarios
  resources :articulos
  resources :proyectos
  resources :eventos
end
  
  root :to => "home#index"
  get "home/blog"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
           can :manage, :all 
    elsif user.has_role? :miembro
            can :read, :all

            cannot :destroy, [Proyecto, User]
            cannot :create, [Proyecto, User]             
     
    end
        
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acta.rb
class Acta < ActiveRecord::Base
end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader

	belongs_to :user
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader
end

app/models/foro.rb
class Foro < ActiveRecord::Base
end

app/models/integrante.rb
class Integrante < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/proyectos_user.rb
class ProyectosUser < ActiveRecord::Base
end

app/models/respuesta.rb
class Respuesta < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


     has_many :articulos



end

app/controllers/respuestas_controller.rb
class RespuestasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_respuesta, only: [:show, :edit, :update, :destroy]

  # GET /respuestas
  # GET /respuestas.json
  def index
    @respuestas = Respuesta.all
  end

  # GET /respuestas/1
  # GET /respuestas/1.json
  def show
  end

  # GET /respuestas/new
  def new
    @respuesta = Respuesta.new
  end

  # GET /respuestas/1/edit
  def edit
  end

  # POST /respuestas
  # POST /respuestas.json
  def create
    @respuesta = Respuesta.new(respuesta_params)

    respond_to do |format|
      if @respuesta.save
        format.html { redirect_to @respuesta, notice: 'Respuesta was successfully created.' }
        format.json { render action: 'show', status: :created, location: @respuesta }
      else
        format.html { render action: 'new' }
        format.json { render json: @respuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /respuestas/1
  # PATCH/PUT /respuestas/1.json
  def update
    respond_to do |format|
      if @respuesta.update(respuesta_params)
        format.html { redirect_to @respuesta, notice: 'Respuesta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @respuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /respuestas/1
  # DELETE /respuestas/1.json
  def destroy
    @respuesta.destroy
    respond_to do |format|
      format.html { redirect_to respuestas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_respuesta
      @respuesta = Respuesta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def respuesta_params
      params.require(:respuesta).permit(:respuesta, :user_id, :articulo_id)
    end
end

app/helpers/actas_helper.rb
module ActasHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/foros_helper.rb
module ForosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/respuestas_helper.rb
module RespuestasHelper
end

app/views/respuestas/_form.html.erb
<%= simple_form_for(@respuesta) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :respuesta %>
    <%= f.input :user_id %>
    <%= f.input :articulo_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/respuestas/edit.html.erb
<h1>Editing respuesta</h1>

<%= render 'form' %>

<%= link_to 'Show', @respuesta %> |
<%= link_to 'Back', respuestas_path %>

app/views/respuestas/index.html.erb
<h1>Listing respuestas</h1>

<table>
  <thead>
    <tr>
      <th>Respuesta</th>
      <th>User</th>
      <th>Articulo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @respuestas.each do |respuesta| %>
      <tr>
        <td><%= respuesta.respuesta %></td>
        <td><%= respuesta.user_id %></td>
        <td><%= respuesta.articulo_id %></td>
        <td><%= link_to 'Show', respuesta %></td>
        <td><%= link_to 'Edit', edit_respuesta_path(respuesta) %></td>
        <td><%= link_to 'Destroy', respuesta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Respuesta', new_respuesta_path %>

app/views/respuestas/new.html.erb
<h1>New respuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', respuestas_path %>

app/views/respuestas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Respuesta:</strong>
  <%= @respuesta.respuesta %>
</p>

<p>
  <strong>User:</strong>
  <%= @respuesta.user_id %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @respuesta.articulo_id %>
</p>

<%= link_to 'Edit', edit_respuesta_path(@respuesta) %> |
<%= link_to 'Back', respuestas_path %>